sessions:
  binance-master:
    exchange: binance
    envVarPrefix: BINANCE
    futures: true
  binance-slave:
    exchange: binance
    envVarPrefix: BINANCE_SLAVE
    futures: true

sync:
  userDataStream:
    trades: true
    filledOrders: true
  sessions:
    - binance-master
    - binance-slave
  symbols:
    - BTCUSDT

crossExchangeStrategies:

- on: binance-master
  copytrader:
    symbol: BTCUSDT
    exchange: binance

#- on: binance-slave
#  copytrader:
#    symbol: BTCUSDT
#    exchange: binance


#  sourceExchange: binanceMaster
#  followerExchange:
#    - binanceMaster
#    - binanceSlave


