---
notifications:
  slack:
    defaultChannel: "bbgo"
    errorChannel: "bbgo-error"

exchangeStrategies:
  - on: max
    marketcap:
      interval: 1m
      baseCurrency: USDT
      targetCurrencies:
        - BTC
        - ETH
      ignoreLocked: true
      threshold: 2%
      # max amount to buy or sell per order
      maxAmount: 10_000
      verbose: true
      dryRun: true

